# Generated by Django 2.0.5 on 2019-03-03 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_last_name', models.CharField(max_length=150)),
                ('patient_first_name', models.CharField(max_length=150)),
                ('patient_middle_name', models.CharField(blank=True, max_length=150)),
                ('age', models.IntegerField(blank=True)),
                ('dob', models.DateTimeField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=5)),
                ('unique_characteristics', models.CharField(blank=True, max_length=1000)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=250)),
                ('next_of_kin_relation', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=25)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTrackingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_tag_num', models.CharField(blank=True, max_length=50)),
                ('tag_color_condition', models.CharField(blank=True, max_length=25)),
                ('mode_of_arrival', models.CharField(blank=True, max_length=25)),
                ('room_number', models.CharField(blank=True, max_length=25)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrival_date', models.DateTimeField(blank=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTrackingDisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition_type', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('updated_condition', models.CharField(blank=True, max_length=25)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('tracking_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientTrackingDetail')),
                ('transfer_to_org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTrackingHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_updated', models.CharField(max_length=5)),
                ('street_address', models.CharField(blank=True, max_length=5)),
                ('city', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_date', models.DateTimeField(blank=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTrackingInjuries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tracking_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientTrackingDetail')),
            ],
        ),
        migrations.AddField(
            model_name='patienttrackingdetail',
            name='tracking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.PatientTrackingHeader'),
        ),
    ]
